CREATE TABLE IF NOT EXISTS user_info (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- H2 自增语法
    name VARCHAR(35),
    phone VARCHAR(35),
    password VARCHAR(35),
    role_id INT
);

insert into user_info(name, phone, password, role_id) values('orangez0', '1234567890', 'password0', 1);
insert into user_info(name, phone, password, role_id) values('orangez1', '1234567891', 'password1', 2);
insert into user_info(name, phone, password, role_id) values('orangez2', '1234567892', 'password2', 1);
insert into user_info(name, phone, password, role_id) values('orangez3', '1234567893', 'password3', 2);
insert into user_info(name, phone, password, role_id) values('orangez4', '1234567894', 'password4', 1);
insert into user_info(name, phone, password, role_id) values('orangez5', '1234567895', 'password5', 2);
insert into user_info(name, phone, password, role_id) values('orangez6', '1234567896', 'password6', 1);
insert into user_info(name, phone, password, role_id) values('orangez7', '1234567897', 'password7', 2);
insert into user_info(name, phone, password, role_id) values('orangez8', '1234567898', 'password8', 1);
insert into user_info(name, phone, password, role_id) values('orangez9', '1234567899', 'password9', 2);